"use client";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "@/redux/providers";
import { LoadingProvider } from "@/components/nprogress/LoadingContext";
import Footer from "@/components/Footer";
import { usePathname} from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const pathname = usePathname()
  const noFooterRoutes = ['/signup', '/login'];
  console.log(pathname, 'pathname')
  return (
    <Providers>

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
        <LoadingProvider> {/* Wrap with LoadingProvider */}
            <Header />
            <main className="flex-grow bg-gray-900">
              {children}
            </main>
            {!noFooterRoutes.includes(pathname) && (
            <Footer/>
            )}
          </LoadingProvider>
      </body>
    </html>
    </Providers>
  );
}
